--- 
title: 'Error Handling' 
description: '予期されるエラーを表示し、キャッチされない例外を処理する方法を学びます。'
related: 
  links: 
    - app/api-reference/file-conventions/error
---

エラーは、**予期されるエラー** と **キャッチされない例外** の2つのカテゴリに分けることができます：

- **予期されるエラーを返り値としてモデル化する**：Server Actionsで予期されるエラーに対して `try`/`catch`を使用することを避けます。これらのエラーを管理し、クライアントに返すために`useFormState`を使用します
- **予期しないエラーにはエラーバウンダリを使用する**：`error.tsx` と `global-error.tsx` ファイルを使用して、予期しないエラーを処理し、フォールバック UI を提供するためにエラーバウンダリを実装します

## 予期されるエラーの処理

予期されるエラーとは、[サーバーサイドのフォームバリデーション](/docs/app/building-your-application/data-fetching/server-actions-and-mutations#server-side-form-validation)やリクエストの失敗など、アプリケーションの通常の操作中に発生する可能性のあるエラーのことです。これらのエラーは明示的に処理され、クライアントに返されるべきです。

### Server Actionsからの予期されるエラーの処理

`useFormState`フックを使用して、Server Actionsの状態を管理し、エラーを処理します。この方法では、予期されるエラーに対して`try`/`catch`ブロックを避け、例外としてスローするのではなく、返り値としてモデル化します。

<Tabs>
<TabItem value="tsx" label="TypeScript">

```tsx title="app/actions.ts" switcher
'use server'

import { redirect } from 'next/navigation'

export async function createUser(prevState: any, formData: FormData) {
  const res = await fetch('https://...')
  const json = await res.json()

  if (!res.ok) {
    return { message: 'Please enter a valid email' }
  }

  redirect('/dashboard')
}
```
</TabItem>
<TabItem value="jsx" label="JavaScript">

```jsx title="app/actions.js" switcher
'use server'

import { redirect } from 'next/navigation'

export async function createUser(prevState, formData) {
  const res = await fetch('https://...')
  const json = await res.json()

  if (!res.ok) {
    return { message: 'Please enter a valid email' }
  }

  redirect('/dashboard')
}
```
</TabItem>
</Tabs>


その後、`useFormState`フックにアクションを渡し、返された`state`を使用してエラーメッセージを表示します。

<Tabs>
<TabItem value="tsx" label="TypeScript">

```tsx title="app/ui/signup.tsx" highlight={11,18-20} switcher
'use client'

import { useFormState } from 'react'
import { createUser } from '@/app/actions'

const initialState = {
  message: '',
}

export function Signup() {
  const [state, formAction] = useFormState(createUser, initialState)

  return (
    <form action={formAction}>
      <label htmlFor="email">Email</label>
      <input type="text" id="email" name="email" required />
      {/* ... */}
      <p aria-live="polite">{state?.message}</p>
      <button>Sign up</button>
    </form>
  )
}
```
</TabItem>
<TabItem value="jsx" label="JavaScript">

```jsx title="app/ui/signup.js" highlight={11,18-20} switcher
'use client'

import { useFormState } from 'react'
import { createUser } from '@/app/actions'

const initialState = {
  message: '',
}

export function Signup() {
  const [state, formAction] = useFormState(createUser, initialState)

  return (
    <form action={formAction}>
      <label htmlFor="email">Email</label>
      <input type="text" id="email" name="email" required />
      {/* ... */}
      <p aria-live="polite">{state?.message}</p>
      <button>Sign up</button>
    </form>
  )
}
```
</TabItem>
</Tabs>


> **Good to know**: これらの例はNext.js App RouterにバンドルされているReactの`useFormState`フックを使用しています。React 19を使用している場合は、代わりに`useActionState`を使用してください。詳細は[Reactドキュメント](https://react.dev/reference/react/useActionState)を参照してください。

返された状態を使用して、クライアントコンポーネントからトーストメッセージを表示することもできます。

### Server Componentsからの予期されるエラーの処理

Server Component内でデータを取得するときに、レスポンスを使用してエラーメッセージを条件付きでレンダリングしたり、[`redirect`](/docs/app/building-your-application/routing/redirecting#redirect-function)を使用することができます。

<Tabs>
<TabItem value="tsx" label="TypeScript">

```tsx title="app/page.tsx" switcher
export default async function Page() {
  const res = await fetch(`https://...`)
  const data = await res.json()

  if (!res.ok) {
    return 'There was an error.'
  }

  return '...'
}
```
</TabItem>
<TabItem value="jsx" label="JavaScript">

```jsx title="app/page.js" switcher
export default async function Page() {
  const res = await fetch(`https://...`)
  const data = await res.json()

  if (!res.ok) {
    return 'There was an error.'
  }

  return '...'
}
```
</TabItem>
</Tabs>


## キャッチされない例外

キャッチされない例外は、アプリケーションの通常のフローで発生すべきでないバグや問題を示す予期しないエラーです。これらはエラーをスローすることで処理され、エラーバウンダリによってキャッチされます。

- **一般的**：`error.js`を使用して、root レイアウトの下でキャッチされないエラーを処理します
- **オプション**：ネストされた`error.js`ファイル（例：`app/dashboard/error.js`）を使用して詳細なキャッチされないエラーを処理します
- **まれ**：`global-error.js`を使用してroot レイアウトでキャッチされないエラーを処理します

### エラーバウンダリの使用

Next.js はエラーバウンダリを使用してキャッチされない例外を処理します。エラーバウンダリは子コンポーネントのエラーをキャッチし、クラッシュしたコンポーネントツリーの代わりにフォールバックUIを表示します。

ルートセグメント内に`error.tsx`ファイルを追加し、Reactコンポーネントをエクスポートすることでエラーバウンダリを作成します：

<Tabs>
<TabItem value="tsx" label="TypeScript">

```tsx title="app/dashboard/error.tsx" switcher
'use client' // エラーバウンダリはクライアントコンポーネントでなければなりません

import { useEffect } from 'react'

export default function Error({
  error,
  reset,
}: {
  error: Error & { digest?: string }
  reset: () => void
}) {
  useEffect(() => {
    // エラーをエラーレポートサービスに記録します
    console.error(error)
  }, [error])

  return (
    <div>
      <h2>Something went wrong!</h2>
      <button
        onClick={
          // セグメントの再レンダリングを試みて回復を試みます
          () => reset()
        }
      >
        Try again
      </button>
    </div>
  )
}
```
</TabItem>
<TabItem value="jsx" label="JavaScript">

```jsx title="app/dashboard/error.js" switcher
'use client' // エラーバウンダリはクライアントコンポーネントでなければなりません

import { useEffect } from 'react'

export default function Error({ error, reset }) {
  useEffect(() => {
    // エラーをエラーレポートサービスに記録します
    console.error(error)
  }, [error])

  return (
    <div>
      <h2>Something went wrong!</h2>
      <button
        onClick={
          // セグメントの再レンダリングを試みて回復を試みます
          () => reset()
        }
      >
        Try again
      </button>
    </div>
  )
}
```
</TabItem>
</Tabs>


エラーを親のエラーバウンダリにバブルアップさせたい場合は、`error`コンポーネントをレンダリングするときに`throw`を使用できます。

### ネストされたルートでのエラーの処理

エラーは最も近い親のエラーバウンダリにバブルアップします。これにより、[ルート階層](/docs/app/building-your-application/routing#component-hierarchy)内の異なるレベルに`error.tsx`ファイルを配置することで、詳細なエラー処理が可能になります。

<Image
  alt="ネストされたエラーコンポーネント階層"
  srcLight="/docs/light/nested-error-component-hierarchy.png"
  srcDark="/docs/dark/nested-error-component-hierarchy.png"
  width="1600"
  height="687"
/>

### グローバルエラーの処理

あまり一般的ではありませんが、[国際化](/docs/app/building-your-application/routing/internationalization)を活用している場合でも、root アプリディレクトリにある`app/global-error.js`を使用して、root レイアウトでエラーを処理することができます。グローバルエラーUIは、アクティブなときにroot レイアウトまたはテンプレートを置き換えるため、自身の`<html>`および`<body>`タグを定義する必要があります。

<Tabs>
<TabItem value="tsx" label="TypeScript">

```tsx title="app/global-error.tsx" switcher
'use client' // エラーバウンダリはクライアントコンポーネントでなければなりません

export default function GlobalError({
  error,
  reset,
}: {
  error: Error & { digest?: string }
  reset: () => void
}) {
  return (
    // global-errorはhtmlとbodyタグを含める必要があります
    <html>
      <body>
        <h2>Something went wrong!</h2>
        <button onClick={() => reset()}>Try again</button>
      </body>
    </html>
  )
}
```
</TabItem>
<TabItem value="jsx" label="JavaScript">

```jsx title="app/global-error.js" switcher
'use client' // エラーバウンダリはクライアントコンポーネントでなければなりません

export default function GlobalError({ error, reset }) {
  return (
    // global-errorはhtmlとbodyタグを含める必要があります
    <html>
      <body>
        <h2>Something went wrong!</h2>
        <button onClick={() => reset()}>Try again</button>
      </body>
    </html>
  )
}
```
</TabItem>
</Tabs>
