---
title: 'Error Handling'
description: '予期されるエラーの表示方法と、キャッチしていない例外の処理方法について学びます。'
related:
  links:
    - app/api-reference/file-conventions/error
---

エラーは2つのカテゴリに分けられます：**予期されるエラー**と**キャッチしていない例外**；

- **予期されるエラーは戻り値としてモデル化する**：Server Actionsで予期されるエラーに対して`try`/`catch`を避ける。これらのエラーを管理し、クライアントに返すために[`useActionState`](https://react.dev/reference/react/useActionState)を使用します
- **予期しないエラーにはエラーボーダリーを使用する**：`error.tsx`および`global-error.tsx`ファイルを使用してエラーボーダリーを実装し、予期しないエラーを処理し、代替UIを提供します

## 予期されるエラーの処理 {#handling-expected-errors}

予期されるエラーは、[サーバーサイドのフォーム検証](/docs/app/building-your-application/data-fetching/server-actions-and-mutations#server-side-form-validation)や失敗したリクエストなど、アプリケーションの通常の操作中に発生する可能性のあるエラーです。これらのエラーは明示的に処理し、クライアントに返す必要があります。

### Server Actionsからの予期されるエラーの処理 {#handling-expected-errors-from-server-actions}

`useActionState`フックを使用してServer Actionsの状態を管理し、エラーを処理します。このアプローチでは、予期されるエラーに対する`try`/`catch`ブロックを回避し、戻り値としてモデル化するべきです。

<Tabs>
<TabItem value="ts" label="TypeScript">

```ts title="app/actions.ts" switcher
'use server'

import { redirect } from 'next/navigation'

export async function createUser(prevState: any, formData: FormData) {
  const res = await fetch('https://...')
  const json = await res.json()

  if (!res.ok) {
    return { message: 'Please enter a valid email' }
  }

  redirect('/dashboard')
}
```

</TabItem>
<TabItem value="js" label="JavaScript">

```js title="app/actions.js" switcher
'use server'

import { redirect } from 'next/navigation'

export async function createUser(prevState, formData) {
  const res = await fetch('https://...')
  const json = await res.json()

  if (!res.ok) {
    return { message: 'Please enter a valid email' }
  }

  redirect('/dashboard')
}
```

</TabItem>
</Tabs>

次に、アクションを`useActionState`フックに渡し、返された`state`を使用してエラーメッセージを表示します。

<Tabs>
<TabItem value="tsx" label="TypeScript">

```tsx title="app/ui/signup.tsx" highlight={11,18-20} switcher
'use client'

import { useActionState } from 'react'
import { createUser } from '@/app/actions'

const initialState = {
  message: '',
}

export function Signup() {
  const [state, formAction, pending] = useActionState(createUser, initialState)

  return (
    <form action={formAction}>
      <label htmlFor="email">Email</label>
      <input type="text" id="email" name="email" required />
      {/* ... */}
      <p aria-live="polite">{state?.message}</p>
      <button disabled={pending}>Sign up</button>
    </form>
  )
}
```

</TabItem>
<TabItem value="jsx" label="JavaScript">

```jsx title="app/ui/signup.js" highlight={11,18-20} switcher
'use client'

import { useActionState } from 'react'
import { createUser } from '@/app/actions'

const initialState = {
  message: '',
}

export function Signup() {
  const [state, formAction, pending] = useActionState(createUser, initialState)

  return (
    <form action={formAction}>
      <label htmlFor="email">Email</label>
      <input type="text" id="email" name="email" required />
      {/* ... */}
      <p aria-live="polite">{state?.message}</p>
      <button disabled={pending}>Sign up</button>
    </form>
  )
}
```

</TabItem>
</Tabs>

返された状態を使用して、クライアントコンポーネントからトーストメッセージを表示することもできます。

### Server Componentsからの予期されるエラーの処理 {#handling-expected-errors-from-server-components}

Server Component内でデータを取得する際に、レスポンスを使用してエラーメッセージを条件付きでレンダリングするか、[`redirect`](/docs/app/building-your-application/routing/redirecting#redirect-function)してください。

<Tabs>
<TabItem value="tsx" label="TypeScript">

```tsx title="app/page.tsx" switcher
export default async function Page() {
  const res = await fetch(`https://...`)
  const data = await res.json()

  if (!res.ok) {
    return 'There was an error.'
  }

  return '...'
}
```

</TabItem>
<TabItem value="jsx" label="JavaScript">

```jsx title="app/page.js" switcher
export default async function Page() {
  const res = await fetch(`https://...`)
  const data = await res.json()

  if (!res.ok) {
    return 'There was an error.'
  }

  return '...'
}
```

</TabItem>
</Tabs>

## キャッチしていない例外 {#uncaught-exceptions}

キャッチしていない例外は、アプリケーションの通常のフロー中に発生すべきでないバグや問題を示す予期しないエラーです。これらはエラーをスローすることにより処理され、その後エラーボーダリーによってキャッチされます。

- **一般的な方法**：root レイアウト以下でのキャッチしていないエラーは`error.js`で処理します
- **オプション**：ネストされた`error.js`ファイル（例：`app/dashboard/error.js`）を使って詳細なキャッチしていないエラーを処理します
- **まれな方法**：root レイアウトでのキャッチしていないエラーは`global-error.js`で処理します

### エラーボーダリーの使用 {#using-error-boundaries}

Next.jsはエラーボーダリーを使用してキャッチしていない例外を処理します。エラーボーダリーはその子コンポーネントで発生したエラーをキャッチし、クラッシュしたコンポーネントツリーの代わりに代替UIを表示します。

エラーボーダリーを作成するには、ルートセグメント内に`error.tsx`ファイルを追加し、Reactコンポーネントをエクスポートしてください:

<Tabs>
<TabItem value="tsx" label="TypeScript">

```tsx title="app/dashboard/error.tsx" switcher
'use client' // Error boundaries must be Client Components

import { useEffect } from 'react'

export default function Error({
  error,
  reset,
}: {
  error: Error & { digest?: string }
  reset: () => void
}) {
  useEffect(() => {
    // Log the error to an error reporting service
    console.error(error)
  }, [error])

  return (
    <div>
      <h2>Something went wrong!</h2>
      <button
        onClick={
          // Attempt to recover by trying to re-render the segment
          () => reset()
        }
      >
        Try again
      </button>
    </div>
  )
}
```

</TabItem>
<TabItem value="jsx" label="JavaScript">

```jsx title="app/dashboard/error.js" switcher
'use client' // Error boundaries must be Client Components

import { useEffect } from 'react'

export default function Error({ error, reset }) {
  useEffect(() => {
    // Log the error to an error reporting service
    console.error(error)
  }, [error])

  return (
    <div>
      <h2>Something went wrong!</h2>
      <button
        onClick={
          // Attempt to recover by trying to re-render the segment
          () => reset()
        }
      >
        Try again
      </button>
    </div>
  )
}
```

</TabItem>
</Tabs>

エラーを親エラーボーダリーまでバブルアップさせたい場合は、`error`コンポーネントをレンダリングする際に`throw`することができます。

### ネストされたルートでのエラー処理 {#handling-errors-in-nested-routes}

エラーは最も近い親エラーボーダリーまでバブルアップします。これにより、[ルート階層](/docs/app/getting-started/project-structure#component-hierarchy)のさまざまなレベルに`error.tsx`ファイルを配置することで詳細なエラー処理が可能になります。

<Image
  alt="ネストされたエラーコンポーネントの階層"
  srcLight="/docs/light/nested-error-component-hierarchy.png"
  srcDark="/docs/dark/nested-error-component-hierarchy.png"
  width="1600"
  height="687"
/>

### グローバルエラーの処理 {#handling-global-errors}

まれではありますが、[国際化](/docs/app/building-your-application/routing/internationalization)を利用している場合でもroot レイアウト内で`app/global-error.js`を使用してエラーを処理できます。グローバルエラーのUIは活性化されると、root レイアウトまたはテンプレートを置換するため、独自の`<html>`および`<body>`タグを定義する必要があります。

<Tabs>
<TabItem value="tsx" label="TypeScript">

```tsx title="app/global-error.tsx" switcher
'use client' // Error boundaries must be Client Components

export default function GlobalError({
  error,
  reset,
}: {
  error: Error & { digest?: string }
  reset: () => void
}) {
  return (
    // global-error must include html and body tags
    <html>
      <body>
        <h2>Something went wrong!</h2>
        <button onClick={() => reset()}>Try again</button>
      </body>
    </html>
  )
}
```

</TabItem>
<TabItem value="jsx" label="JavaScript">

```jsx title="app/global-error.js" switcher
'use client' // Error boundaries must be Client Components

export default function GlobalError({ error, reset }) {
  return (
    // global-error must include html and body tags
    <html>
      <body>
        <h2>Something went wrong!</h2>
        <button onClick={() => reset()}>Try again</button>
      </body>
    </html>
  )
}
```

</TabItem>
</Tabs>
