---
title: 'エラーハンドリング'
description: '期待されたエラーの表示方法とキャッチされない例外の処理方法について学びましょう。'
related:
  links:
    - app/api-reference/file-conventions/error
---

エラーは**期待されたエラー**と**キャッチされない例外**の2つに分類できます：

- **期待されたエラーを返り値としてモデル化する**：Server Actionsでは、期待されたエラーに対して`try`/`catch`を使用しないでください。これらのエラーは、[`useActionState`](https://react.dev/reference/react/useActionState)を使用して管理し、クライアントに返します。
- **予期しないエラーをerror boundaryで処理する**：予期しないエラーを処理し、フォールバックUIを提供するために、`error.tsx`および`global-error.tsx`ファイルを使用してエラーバウンダリーを実装します。

## 期待されたエラーを処理する {#handling-expected-errors}

期待されたエラーは、通常のアプリケーション操作中に発生する可能性があるエラーであり、[サーバーサイドのフォーム検証](/docs/app/building-your-application/data-fetching/server-actions-and-mutations#server-side-form-validation)や失敗したリクエストなどです。これらのエラーは明示的に処理し、クライアントに返す必要があります。

### サーバーアクションからの期待されたエラーを処理する {#handling-expected-errors-from-server-actions}

`useActionState`フックを使用して、エラー処理を含むサーバーアクションの状態を管理します。このアプローチは、期待されたエラーに対して`try`/`catch`ブロックを避け、例外ではなく戻り値としてモデル化するべきです。

<Tabs>
<TabItem value="tsx" label="TypeScript">

```tsx title="app/actions.ts" switcher
'use server'

import { redirect } from 'next/navigation'

export async function createUser(prevState: any, formData: FormData) {
  const res = await fetch('https://...')
  const json = await res.json()

  if (!res.ok) {
    return { message: '有効なメールアドレスを入力してください' }
  }

  redirect('/dashboard')
}
```

</TabItem>
<TabItem value="jsx" label="JavaScript">

```jsx title="app/actions.js" switcher
'use server'

import { redirect } from 'next/navigation'

export async function createUser(prevState, formData) {
  const res = await fetch('https://...')
  const json = await res.json()

  if (!res.ok) {
    return { message: '有効なメールアドレスを入力してください' }
  }

  redirect('/dashboard')
}
```

</TabItem>
</Tabs>

次に、アクションを`useActionState`フックに渡し、返された`state`を使用してエラーメッセージを表示できます。

<Tabs>
<TabItem value="tsx" label="TypeScript">

```tsx title="app/ui/signup.tsx" highlight={11,18-20} switcher
'use client'

import { useActionState } from 'react'
import { createUser } from '@/app/actions'

const initialState = {
  message: '',
}

export function Signup() {
  const [state, formAction, pending] = useActionState(createUser, initialState)

  return (
    <form action={formAction}>
      <label htmlFor="email">Email</label>
      <input type="text" id="email" name="email" required />
      {/* ... */}
      <p aria-live="polite">{state?.message}</p>
      <button disabled={pending}>Sign up</button>
    </form>
  )
}
```

</TabItem>
<TabItem value="jsx" label="JavaScript">

```jsx title="app/ui/signup.js" highlight={11,18-20} switcher
'use client'

import { useActionState } from 'react'
import { createUser } from '@/app/actions'

const initialState = {
  message: '',
}

export function Signup() {
  const [state, formAction, pending] = useActionState(createUser, initialState)

  return (
    <form action={formAction}>
      <label htmlFor="email">Email</label>
      <input type="text" id="email" name="email" required />
      {/* ... */}
      <p aria-live="polite">{state?.message}</p>
      <button disabled={pending}>Sign up</button>
    </form>
  )
}
```

</TabItem>
</Tabs>

また、返された状態を使用して、クライアントコンポーネントからトーストメッセージを表示することもできます。

### サーバーコンポーネントからの期待されたエラーを処理する {#handling-expected-errors-from-server-components}

Server Component内でデータを取得する際に、レスポンスを使用してエラーメッセージを条件付きでレンダリングしたり、[`redirect`](/docs/app/building-your-application/routing/redirecting#redirect-function)したりすることができます。

<Tabs>
<TabItem value="tsx" label="TypeScript">

```tsx title="app/page.tsx" switcher
export default async function Page() {
  const res = await fetch(`https://...`)
  const data = await res.json()

  if (!res.ok) {
    return 'エラーが発生しました。'
  }

  return '...'
}
```

</TabItem>
<TabItem value="jsx" label="JavaScript">

```jsx title="app/page.js" switcher
export default async function Page() {
  const res = await fetch(`https://...`)
  const data = await res.json()

  if (!res.ok) {
    return 'エラーが発生しました。'
  }

  return '...'
}
```

</TabItem>
</Tabs>

## キャッチされない例外 {#uncaught-exceptions}

キャッチされない例外は、バグやアプリケーションの通常のフロー中に発生すべきではない問題を示す予期しないエラーです。これらはエラーをスローすることによって処理され、その後、error boundaryにキャッチされます。

- **一般的な方法:** root レイアウト以下の未キャッチエラーを`error.js`で処理します。
- **オプション:** ネストされた`error.js`ファイル（例えば`app/dashboard/error.js`）で細かい未キャッチエラーを処理します。
- **まれな方法:** ルートレイアウトで未キャッチエラーを`global-error.js`で処理します。

### エラーバウンダリーの使用 {#using-error-boundaries}

Next.jsでは、エラーバウンダリーを使用してキャッチされない例外を処理します。エラーバウンダリーは、子コンポーネントで発生したエラーをキャッチし、クラッシュしたコンポーネントツリーの代わりにフォールバックUIを表示します。

ルートセグメント内に`error.tsx`ファイルを追加し、Reactコンポーネントをエクスポートすることでエラーバウンダリーを作成します：

<Tabs>
<TabItem value="tsx" label="TypeScript">

```tsx title="app/dashboard/error.tsx" switcher
'use client' // エラーバウンダリーはクライアントコンポーネントである必要があります

import { useEffect } from 'react'

export default function Error({
  error,
  reset,
}: {
  error: Error & { digest?: string }
  reset: () => void
}) {
  useEffect(() => {
    // エラーをエラーレポートサービスに記録する
    console.error(error)
  }, [error])

  return (
    <div>
      <h2>何かがうまくいきませんでした！</h2>
      <button
        onClick={
          // セグメントを再レンダリングして回復を試みる
          () => reset()
        }
      >
        もう一度試す
      </button>
    </div>
  )
}
```

</TabItem>
<TabItem value="jsx" label="JavaScript">

```jsx title="app/dashboard/error.js" switcher
'use client' // エラーバウンダリーはクライアントコンポーネントである必要があります

import { useEffect } from 'react'

export default function Error({ error, reset }) {
  useEffect(() => {
    // エラーをエラーレポートサービスに記録する
    console.error(error)
  }, [error])

  return (
    <div>
      <h2>何かがうまくいきませんでした！</h2>
      <button
        onClick={
          // セグメントを再レンダリングして回復を試みる
          () => reset()
        }
      >
        もう一度試す
      </button>
    </div>
  )
}
```

</TabItem>
</Tabs>

エラーが親のerror boundaryにバブルアップすることを望む場合は、`error`コンポーネントをレンダリングするときに`throw`を使用できます。

### ネストされたルートでのエラー処理 {#handling-errors-in-nested-routes}

エラーは最も近い親のエラーバウンダリーにバブルアップします。これにより、[ルート階層](/docs/app/building-your-application/routing#component-hierarchy)の異なるレベルに`error.tsx`ファイルを配置することで、細かいエラー処理が可能になります。

<Image
  alt="ネストされたエラーコンポーネントの階層"
  srcLight="/docs/light/nested-error-component-hierarchy.png"
  srcDark="/docs/dark/nested-error-component-hierarchy.png"
  width="1600"
  height="687"
/>

### グローバルエラーの処理 {#handling-global-errors}

あまり一般的ではありませんが、[国際化](/docs/app/building-your-application/routing/internationalization)を利用する際も、ルートアプリディレクトリ内にある`app/global-error.js`を使用してroot レイアウトでエラーを処理することができます。グローバルエラーUIはアクティブなときにルートレイアウトまたはテンプレートを置き換えるため、自身の`<html>`および`<body>`タグを定義する必要があります。

<Tabs>
<TabItem value="tsx" label="TypeScript">

```tsx title="app/global-error.tsx" switcher
'use client' // エラーバウンダリーはクライアントコンポーネントである必要があります

export default function GlobalError({
  error,
  reset,
}: {
  error: Error & { digest?: string }
  reset: () => void
}) {
  return (
    // global-errorにはhtmlとbodyタグを含める必要があります
    <html>
      <body>
        <h2>何かがうまくいきませんでした！</h2>
        <button onClick={() => reset()}>もう一度試す</button>
      </body>
    </html>
  )
}
```

</TabItem>
<TabItem value="jsx" label="JavaScript">

```jsx title="app/global-error.js" switcher
'use client' // エラーバウンダリーはクライアントコンポーネントである必要があります

export default function GlobalError({ error, reset }) {
  return (
    // global-errorにはhtmlとbodyタグを含める必要があります
    <html>
      <body>
        <h2>何かがうまくいきませんでした！</h2>
        <button onClick={() => reset()}>もう一度試す</button>
      </body>
    </html>
  )
}
```

</TabItem>
</Tabs>
