---
title: 'Error Handling'
description: '予期されるエラーの表示方法と、キャッチされない例外の処理方法を学ぶ。'
related:
  links:
    - app/api-reference/file-conventions/error
---

エラーは、「**予期されるエラー**」と「**キャッチされない例外**」の2つに分類できます：

- **予期されるエラーを戻り値としてモデル化する**：Server Actionsで予期されるエラーに対して `try`/`catch`を使用するのは避けてください。これらのエラーを管理し、クライアントに返すために[`useActionState`](https://react.dev/reference/react/useActionState)を使用します。
- **予期しないエラーにはerror boundaryを使用する**：予期しないエラーを処理し、フォールバックUIを提供するために、`error.tsx`と`global-error.tsx`ファイルを使用してerror boundaryを実装します。

## 予期されるエラーの処理 {#handling-expected-errors}

予期されるエラーとは、アプリケーションの通常の動作中に発生する可能性のあるエラー（[サーバーサイドフォームのバリデーション](/docs/app/building-your-application/data-fetching/server-actions-and-mutations#server-side-form-validation)や失敗したリクエストなど）が含まれます。これらのエラーは明示的に処理され、クライアントに返す必要があります。

### Server Actionsからの予期されるエラーの処理 {#handling-expected-errors-from-server-actions}

Server Actionsの状態を管理するために`useActionState`フックを使用し、エラーの処理を行います。このアプローチは、予期されるエラーのための`try`/`catch`ブロックを回避し、例外ではなく戻り値としてエラーをモデル化します。

<Tabs>
<TabItem value="tsx" label="TypeScript">

```tsx title="app/actions.ts" switcher
'use server'

import { redirect } from 'next/navigation'

export async function createUser(prevState: any, formData: FormData) {
  const res = await fetch('https://...')
  const json = await res.json()

  if (!res.ok) {
    return { message: 'Please enter a valid email' }
  }

  redirect('/dashboard')
}
```

</TabItem>
<TabItem value="jsx" label="JavaScript">

```jsx title="app/actions.js" switcher
'use server'

import { redirect } from 'next/navigation'

export async function createUser(prevState, formData) {
  const res = await fetch('https://...')
  const json = await res.json()

  if (!res.ok) {
    return { message: 'Please enter a valid email' }
  }

  redirect('/dashboard')
}
```

</TabItem>
</Tabs>

その後、アクションを`useActionState`フックに渡し、返された`state`を使用してエラーメッセージを表示できます。

<Tabs>
<TabItem value="tsx" label="TypeScript">

```tsx title="app/ui/signup.tsx" highlight={11,18-20} switcher
'use client'

import { useActionState } from 'react'
import { createUser } from '@/app/actions'

const initialState = {
  message: '',
}

export function Signup() {
  const [state, formAction, pending] = useActionState(createUser, initialState)

  return (
    <form action={formAction}>
      <label htmlFor="email">Email</label>
      <input type="text" id="email" name="email" required />
      {/* ... */}
      <p aria-live="polite">{state?.message}</p>
      <button disabled={pending}>Sign up</button>
    </form>
  )
}
```

</TabItem>
<TabItem value="jsx" label="JavaScript">

```jsx title="app/ui/signup.js" highlight={11,18-20} switcher
'use client'

import { useActionState } from 'react'
import { createUser } from '@/app/actions'

const initialState = {
  message: '',
}

export function Signup() {
  const [state, formAction, pending] = useActionState(createUser, initialState)

  return (
    <form action={formAction}>
      <label htmlFor="email">Email</label>
      <input type="text" id="email" name="email" required />
      {/* ... */}
      <p aria-live="polite">{state?.message}</p>
      <button disabled={pending}>Sign up</button>
    </form>
  )
}
```

</TabItem>
</Tabs>

返されたstateを使用して、クライアントコンポーネントからトーストメッセージを表示することもできます。

### Server Componentからの予期されるエラーの処理 {#handling-expected-errors-from-server-components}

Server Component内でデータをフェッチするとき、レスポンスを使ってエラーメッセージを条件付きでレンダリングしたり、[`redirect`](/docs/app/building-your-application/routing/redirecting#redirect-function)を使用することができます。

<Tabs>
<TabItem value="tsx" label="TypeScript">

```tsx title="app/page.tsx" switcher
export default async function Page() {
  const res = await fetch(`https://...`)
  const data = await res.json()

  if (!res.ok) {
    return 'There was an error.'
  }

  return '...'
}
```

</TabItem>
<TabItem value="jsx" label="JavaScript">

```jsx title="app/page.js" switcher
export default async function Page() {
  const res = await fetch(`https://...`)
  const data = await res.json()

  if (!res.ok) {
    return 'There was an error.'
  }

  return '...'
}
```

</TabItem>
</Tabs>

## キャッチされない例外 {#uncaught-exceptions}

キャッチされない例外は、バグやアプリケーションの通常のフロー中に発生すべきでない問題を示す予期されないエラーです。これらはエラーをスローすることで処理され、その後error boundaryによってキャッチされます。

- **一般的**: `error.js`を使用してroot レイアウト以下のキャッチされないエラーを処理します。
- **オプション**: ネストされた`error.js`（例：`app/dashboard/error.js`）ファイルを使用して詳細なキャッチされないエラーを処理します。
- **希なケース**: `global-error.js`を使用してroot レイアウト内のキャッチされないエラーを処理します。

### Error Boundaryの使用 {#using-error-boundaries}

Next.jsはキャッチされない例外を処理するためにerror boundaryを使用します。error boundaryは子コンポーネント内のエラーをキャッチし、クラッシュしたコンポーネントtreeの代わりにフォールバックUIを表示します。

route segment内に `error.tsx` ファイルを追加し、Reactコンポーネントをエクスポートすることでerror boundaryを作成します：

<Tabs>
<TabItem value="tsx" label="TypeScript">

```tsx title="app/dashboard/error.tsx" switcher
'use client' // Error boundaries must be Client Components

import { useEffect } from 'react'

export default function Error({
  error,
  reset,
}: {
  error: Error & { digest?: string }
  reset: () => void
}) {
  useEffect(() => {
    // エラーをエラーレポーティングサービスにログとして記録します;
    console.error(error)
  }, [error])

  return (
    <div>
      <h2>何か問題が発生しました！</h2>
      <button
        onClick={
          // セグメントを再描画して回復を試みます;
          () => reset()
        }
      >
        もう一度試す
      </button>
    </div>
  )
}
```

</TabItem>
<TabItem value="jsx" label="JavaScript">

```jsx title="app/dashboard/error.js" switcher
'use client' // Error boundaries must be Client Components

import { useEffect } from 'react'

export default function Error({ error, reset }) {
  useEffect(() => {
    // エラーをエラーレポーティングサービスにログとして記録します;
    console.error(error)
  }, [error])

  return (
    <div>
      <h2>何か問題が発生しました！</h2>
      <button
        onClick={
          // セグメントを再描画して回復を試みます;
          () => reset()
        }
      >
        もう一度試す
      </button>
    </div>
  )
}
```

</TabItem>
</Tabs>

エラーを親のerror boundaryに伝播させたい場合は、`error`コンポーネントをレンダリングする際に`throw`することができます。

### ネストされたルートでのエラー処理 {#handling-errors-in-nested-routes}

エラーは最も近い親のerror boundaryに伝播します。これにより、[route階層](/docs/app/building-your-application/routing#component-hierarchy)の異なるレベルに`error.tsx`ファイルを配置することで、詳細なエラー処理が可能になります。

<Image
  alt="ネストされたエラーコンポーネント階層"
  srcLight="/docs/light/nested-error-component-hierarchy.png"
  srcDark="/docs/dark/nested-error-component-hierarchy.png"
  width="1600"
  height="687"
/>

### グローバルエラーの処理 {#handling-global-errors}

希ではありますが、[国際化](/docs/app/building-your-application/routing/internationalization)を活用する場合でも、root レイアウト内で発生したエラーをrootアプリディレクトリにある`app/global-error.js`を使用して処理することが可能です。グローバルエラーのUIは、アクティブの際にroot レイアウトまたはテンプレートの代わりとなるため、自身の`<html>`と`<body>`タグを定義する必要があります。

<Tabs>
<TabItem value="tsx" label="TypeScript">

```tsx title="app/global-error.tsx" switcher
'use client' // Error boundaries must be Client Components

export default function GlobalError({
  error,
  reset,
}: {
  error: Error & { digest?: string }
  reset: () => void
}) {
  return (
    // global-errorにはhtmlとbodyタグを含める必要があります;
    <html>
      <body>
        <h2>何か問題が発生しました！</h2>
        <button onClick={() => reset()}>もう一度試す</button>
      </body>
    </html>
  )
}
```

</TabItem>
<TabItem value="jsx" label="JavaScript">

```jsx title="app/global-error.js" switcher
'use client' // Error boundaries must be Client Components

export default function GlobalError({ error, reset }) {
  return (
    // global-errorにはhtmlとbodyタグを含める必要があります;
    <html>
      <body>
        <h2>何か問題が発生しました！</h2>
        <button onClick={() => reset()}>もう一度試す</button>
      </body>
    </html>
  )
}
```

</TabItem>
</Tabs>
